# bash says that the binary is not found on alpine
FROM rust:alpine

WORKDIR /app
COPY . .

RUN apk add --no-cache musl-dev
RUN cargo build --release
RUN mv target/release/depot .

ENTRYPOINT ["./depot"]

