FROM archlinux/archlinux

WORKDIR /app
RUN pacman -Sy --noconfirm

RUN pacman -S --noconfirm gcc rustup
RUN rustup default stable
COPY . .

RUN cargo build --release
RUN mv target/release/depot .

ENTRYPOINT ["./depot"]

